#!/usr/bin/env bash

# Update package list
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Ensure correct permissions and ownership for the web root directory
sudo chown -R www-data:www-data /var/www/html
sudo chmod -R 755 /var/www/html

# Modify the default index.html file
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Start the Nginx service
sudo service nginx start
