#!/usr/bin/env bash
# Configure Haproxy to evenly distribute
# traffics using roundrobin to both
# web-01 and web-02 servers

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend http_back
    
backend http_back
    balance roundrobin
    server 502930-web-01 52.87.216.174:80 check
    server 502930-web-02 35.153.194.177:80 check
"
# Update packages
sudo apt-get -y update
sudo apt-get -y upgrade

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy and copy the content of balancer to /etc/haproxy/haproxy.cfg
sudo apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg

#restart Haproxy
sudo service haproxy restart
