#!/usr/bin/env bash
# backup database
# Check if the password argument is provided
if [ $# -ne 1 ]; then
	echo "Usage: $0 <mysql_root_password>"
	exit 1
fi
# MySQL root password
MYSQL_ROOT_PASSWORD=$1

# Date format for the archive name
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"

# Generate MySQL dump
mysqldump --all-databases -u root --password="$MYSQL_ROOT_PASSWORD" > backup.sql

# Check if the dump was successful
if [ $? -ne 0 ]; then
	echo "MySQL dump failed!"
	exit 1
fi

# Compress the dump file
tar -czvf "$file_name" backup.sql

# Check if the compression was successful
if [ $? -ne 0 ]; then
	echo "Compression failed!"
	exit 1
fi
# Check if the tar.gz file is properly gzipped
file_output=$(file "$file_name")
if [[ "$file_output" != *"gzip compressed data"* ]]; then
	echo "The tar.gz file is not properly gzipped!"
	rm -f "$file_name"  # Cleanup the invalid tar.gz file
	rm -f backup.sql  # Cleanup the dump file
	exit 1
fi


# Remove the uncompressed dump file
rm backup.sql

echo "Backup successful! Archive created: $file_name"
